CREATE TABLE Publisher (
	Id BIGINT IDENTITY,
	Name VARCHAR(128) NOT NULL
);

CREATE TABLE Movie (
	Id BIGINT IDENTITY,
	Title VARCHAR(128) NOT NULL,
	Year INTEGER NOT NULL,
	Publisher_Id BIGINT FOREIGN KEY REFERENCES Publisher(Id)
);